swagger: '2.0'
basePath: /ab
info:
  title: Kontakty
  version: '1.0'
  description: Książka adresowa
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: Branches
    description: oddziały
  - name: Contacts
    description: oddziały
definitions:
  Branch:
    type: object
    properties:
      id:
        type: string
        description: identyfikator
      branch:
        type: string
        description: nazwa grupy / wydziału
      bcode:
        type: string
        description: kod grupy (skrót)
  Branches:
    type: object
    properties:
      branches:
        type: array
        items:
            $ref: '#/definitions/Branch'
  Contact:
    type: object
    properties:
      bcode:
        type: string
        description: nazwisko
      name:
        type: string
        description: nazwisko
      email:
        type: string
        description: email
      phone:
        type: string
        description: telefon
      function:
        type: string
        description: stanowisko
      notes:
        type: string
        description: uwagi
  Contacts:
    type: object
    properties:
      contacts:
        type: array
        items:
            $ref: '#/definitions/Contact'
  Error:
    type: object
    properties:
      message:
        type: string
        description: ret. message
      retcode:
        type: number
        description: ret. code
paths:
  /branches:
    get:
      operationId: getBranches
      responses:
        '200':
          description: Sukces - lista wydziałów
          schema:
            $ref: '#/definitions/Branches'
        '500':
          description: Błąd wewnętrzny.
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Branches
  /contacts:
    get:
      operationId: getContacts
      parameters:
        - in: query
          name: bcode
          type: string
          description: identyfikator grupy / wydziału
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Contacts'
        '500':
          description: Błąd wewnętrzny.
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Contacts
